# Generated by Django 2.1.5 on 2020-10-31 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Product Title')),
                ('price', models.FloatField()),
                ('uploaded_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='uploaded_date')),
                ('my_float', models.FloatField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'csv_product',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='csv_product',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.customer'),
        ),
    ]
