# Generated by Django 2.1.5 on 2020-10-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201031_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_product',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
