# Generated by Django 2.1.5 on 2020-10-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201031_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='csv_product',
            old_name='title',
            new_name='product_title',
        ),
    ]
