# Generated by Django 2.1.5 on 2020-10-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201031_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='csv_product',
            old_name='product_title',
            new_name='title',
        ),
    ]
